create table if not exists public.chat_folders (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, position int not null default 0, created_at timestamptz not null default now());
create table if not exists public.chat_folder_items (user_id uuid not null references auth.users(id) on delete cascade, folder_id uuid not null references public.chat_folders(id) on delete cascade, chat_id uuid not null references public.chats(id) on delete cascade, primary key(user_id,folder_id,chat_id));
create table if not exists public.chat_user_settings (user_id uuid not null references auth.users(id) on delete cascade, chat_id uuid not null references public.chats(id) on delete cascade, archived boolean not null default false, primary key(user_id,chat_id));
create table if not exists public.blocked_users (user_id uuid not null references auth.users(id) on delete cascade, blocked_user_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id,blocked_user_id));
alter table public.chat_folders enable row level security; alter table public.chat_folder_items enable row level security; alter table public.chat_user_settings enable row level security; alter table public.blocked_users enable row level security;
drop policy if exists chat_folders_owner on public.chat_folders; create policy chat_folders_owner on public.chat_folders for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists chat_folder_items_owner on public.chat_folder_items; create policy chat_folder_items_owner on public.chat_folder_items for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists chat_user_settings_owner on public.chat_user_settings; create policy chat_user_settings_owner on public.chat_user_settings for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists blocked_users_owner on public.blocked_users; create policy blocked_users_owner on public.blocked_users for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
