import { useState, useEffect, useCallback, useRef } from 'react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/auth'
import { Chat, Profile, ChatMember } from '../lib/types'
import { Plus, Search, Settings, Trash2, Shield, Download, Bookmark, Archive, Folder, FolderPlus, X, Ban, MoreVertical } from 'lucide-react'
import Avatar from './Avatar'
import InstallModal from './InstallModal'

interface ChatListProps { selectedId: string; onSelect: (id: string) => void; onNewChat: () => void; onSettings: () => void; onAdmin: () => void; onPreviewChat: (id: string) => void }
interface ChatWithMeta extends Chat { other_user?: Profile | null; last_message?: string | null; last_message_time?: string | null; other_online?: boolean; unread_count?: number }

type FolderState = { id:string; name:string; chatIds:string[] }
const FOLDER_KEY=(uid:string)=>`sira-chat-folders:${uid}`
const ARCHIVE_KEY=(uid:string)=>`sira-chat-archive:${uid}`
const BLOCK_KEY=(uid:string)=>`sira-blocked:${uid}`
function readJSON<T>(key:string, fallback:T):T { try { const x=localStorage.getItem(key); return x?JSON.parse(x):fallback } catch { return fallback } }

export default function ChatList({ selectedId, onSelect, onNewChat, onSettings, onAdmin, onPreviewChat }: ChatListProps) {
  const { user, profile } = useAuth()
  const [chats,setChats]=useState<ChatWithMeta[]>([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true)
  const [unreadCounts,setUnreadCounts]=useState<Record<string,number>>({}),[publicResults,setPublicResults]=useState<Chat[]>([]),[searchingPublic,setSearchingPublic]=useState(false)
  const [menuChatId,setMenuChatId]=useState<string|null>(null),[showInstall,setShowInstall]=useState(false)
  const [folders,setFolders]=useState<FolderState[]>([]),[activeFolder,setActiveFolder]=useState('all'),[showFolderCreator,setShowFolderCreator]=useState(false),[newFolder,setNewFolder]=useState('')
  const [archived,setArchived]=useState<string[]>([]),[blocked,setBlocked]=useState<string[]>([]),[selected,setSelected]=useState<Set<string>>(new Set())
  const pressTimer=useRef<any>(null),longPressed=useRef(false)

  useEffect(()=>{ if(!user)return; setFolders(readJSON(FOLDER_KEY(user.id),[])); setArchived(readJSON(ARCHIVE_KEY(user.id),[])); setBlocked(readJSON(BLOCK_KEY(user.id),[])) },[user?.id])
  const persistFolders=(v:FolderState[])=>{setFolders(v);if(user)localStorage.setItem(FOLDER_KEY(user.id),JSON.stringify(v))}
  const persistArchived=(v:string[])=>{setArchived(v);if(user)localStorage.setItem(ARCHIVE_KEY(user.id),JSON.stringify(v))}
  const persistBlocked=(v:string[])=>{setBlocked(v);if(user)localStorage.setItem(BLOCK_KEY(user.id),JSON.stringify(v))}

  const loadChats=useCallback(async()=>{
    if(!user)return
    const {data:mem}=await supabase.from('chat_members').select('chat_id').eq('user_id',user.id)
    if(!mem?.length){setChats([]);setLoading(false);return}
    const ids=mem.map((m:any)=>m.chat_id)
    const {data:cs}=await supabase.from('chats').select('*').in('id',ids)
    if(!cs){setChats([]);setLoading(false);return}
    const {data:members}=await supabase.from('chat_members').select('chat_id,user_id,role').in('chat_id',ids)
    const uids=[...new Set((members||[]).map((m:any)=>m.user_id))]
    const {data:ps}=await supabase.from('profiles').select('*').in('id',uids as string[])
    const pm:Record<string,Profile>={};for(const x of (ps||[]) as Profile[])pm[x.id]=x
    const map:Record<string,ChatWithMeta>={};for(const c of cs as Chat[])map[c.id]={...c,other_user:null,other_online:false}
    for(const m of (members||[]) as ChatMember[]){const c=map[m.chat_id];if(c&&c.type==='direct'&&m.user_id!==user.id){c.other_user=pm[m.user_id];c.other_online=!!pm[m.user_id]?.is_online}}
    for(const c of Object.values(map)){if(c.type==='direct'&&c.other_user){c.title=c.other_user.display_name||c.other_user.username;c.avatar_url=c.other_user.avatar_url}if(!c.title)c.title=c.type==='group'?'گروه':c.type==='saved'?'پیام‌های ذخیره شده':'گفت‌وگو'}
    const {data:msgs}=await supabase.from('messages').select('chat_id,content,created_at,deleted_at,message_type,file_name').in('chat_id',ids).order('created_at',{ascending:false}).limit(100)
    for(const m of (msgs||[]) as any[]){const c=map[m.chat_id];if(c&&!c.last_message_time){c.last_message_time=m.created_at;c.last_message=m.deleted_at?'پیام حذف شد':m.message_type==='image'?'📷 تصویر':m.message_type==='file'?(m.file_name?.match(/\.(mp3|wav|m4a|ogg|aac|flac)$/i)?'🎵 آهنگ':'📎 فایل'):m.message_type==='voice'?'🎤 پیام صوتی':m.content}}
    setChats(Object.values(map).sort((a,b)=>{if(a.type==='saved'&&b.type!=='saved')return -1;if(b.type==='saved'&&a.type!=='saved')return 1;return (new Date(b.last_message_time||b.created_at).getTime())-(new Date(a.last_message_time||a.created_at).getTime())}));setLoading(false)
  },[user])
  const loadUnread=useCallback(async()=>{if(!user)return;const {data:mem}=await supabase.from('chat_members').select('chat_id').eq('user_id',user.id);const ids=(mem||[]).map((m:any)=>m.chat_id);if(!ids.length){setUnreadCounts({});return};const {data:ms}=await supabase.from('messages').select('chat_id').in('chat_id',ids).neq('sender_id',user.id).is('read_at',null).is('deleted_at',null);const c:Record<string,number>={};for(const m of (ms||[]) as any[])c[m.chat_id]=(c[m.chat_id]||0)+1;setUnreadCounts(c)},[user])
  useEffect(()=>{loadChats();loadUnread()},[loadChats,loadUnread])
  useEffect(()=>{const ch=supabase.channel('chat-list-updates-v2').on('postgres_changes',{event:'*',schema:'public',table:'chat_members',filter:`user_id=eq.${user?.id||''}`},loadChats).on('postgres_changes',{event:'*',schema:'public',table:'chats'},loadChats).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},()=>{loadChats();loadUnread()}).subscribe();const f=()=>{loadChats();loadUnread()};window.addEventListener('chat-list-reload',f);return()=>{supabase.removeChannel(ch);window.removeEventListener('chat-list-reload',f)}},[loadChats,loadUnread,user?.id])
  useEffect(()=>{if(!user||!search.trim()){setPublicResults([]);return};const q=search.trim().toLowerCase();setSearchingPublic(true);const t=setTimeout(async()=>{const {data:mem}=await supabase.from('chat_members').select('chat_id').eq('user_id',user.id);const ids=new Set((mem||[]).map((m:any)=>m.chat_id));const {data:cs}=await supabase.from('chats').select('*').in('type',['group','channel']).eq('is_private',false).or(`title.ilike.%${q}%,username.ilike.%${q}%`).limit(20);setPublicResults(((cs||[]) as Chat[]).filter(c=>!ids.has(c.id)));setSearchingPublic(false)},300);return()=>clearTimeout(t)},[search,user])

  const deleteChat=async(id:string,owner:boolean)=>{if(!user)return;if(owner){await supabase.from('chat_members').delete().eq('chat_id',id);await supabase.from('chats').delete().eq('id',id)}else await supabase.from('chat_members').delete().eq('chat_id',id).eq('user_id',user.id);setChats(v=>v.filter(c=>c.id!==id));if(selectedId===id)onSelect('');setMenuChatId(null)}
  const toggleArchive=(id:string)=>persistArchived(archived.includes(id)?archived.filter(x=>x!==id):[...archived,id])
  const addFolder=(id:string, folderId=activeFolder)=>{if(folderId==='all'||folderId==='archived')return;persistFolders(folders.map(f=>f.id===folderId?{...f,chatIds:[...new Set([...f.chatIds,id])]}:f));setMenuChatId(null)}
  const removeFromFolder=(id:string)=>{if(activeFolder==='all')return;persistFolders(folders.map(f=>f.id===activeFolder?{...f,chatIds:f.chatIds.filter(x=>x!==id)}:f));setMenuChatId(null)}
  const createFolder=()=>{const n=newFolder.trim();if(!n)return;persistFolders([...folders,{id:`f-${Date.now()}`,name:n,chatIds:[]}]);setNewFolder('');setShowFolderCreator(false)}
  const block=(chat:ChatWithMeta)=>{const id=chat.other_user?.id;if(!id)return;persistBlocked([...new Set([...blocked,id])]);setMenuChatId(null)}
  const startPress=(id:string)=>{longPressed.current=false;pressTimer.current=setTimeout(()=>{longPressed.current=true;setSelected(v=>{const n=new Set(v);n.has(id)?n.delete(id):n.add(id);return n})},550)}
  const endPress=()=>{if(pressTimer.current)clearTimeout(pressTimer.current)}
  const filtered=chats.filter(c=>{if(blocked.includes(c.other_user?.id||''))return false;if(activeFolder==='archived')return archived.includes(c.id);if(activeFolder!=='all'&&!folders.find(f=>f.id===activeFolder)?.chatIds.includes(c.id))return false;if(activeFolder==='all'&&archived.includes(c.id))return false;const q=search.toLowerCase();return !q||(c.title||'').toLowerCase().includes(q)||(c.other_user?.phone||'').toLowerCase().includes(q)||(c.other_user?.username||'').toLowerCase().includes(q)})
  const allCount=chats.filter(c=>!archived.includes(c.id)&&!blocked.includes(c.other_user?.id||'')).length

  return <div className="w-full md:w-80 md:max-w-80 h-full bg-tg-panel flex flex-col border-l border-tg-border relative" onClick={()=>{if(menuChatId)setMenuChatId(null)}}>
    <div className="flex items-center gap-2 p-3 bg-tg-panel"><h1 className="text-lg font-bold text-tg-text flex-1">سیرا چت</h1>{profile?.is_admin&&<button onClick={onAdmin} className="w-9 h-9 rounded-full hover:bg-tg-hover flex items-center justify-center text-tg-accent"><Shield size={20}/></button>}<button onClick={()=>setShowInstall(true)} className="w-9 h-9 rounded-full hover:bg-tg-hover flex items-center justify-center text-tg-subtext"><Download size={20}/></button><button onClick={onSettings} className="w-9 h-9 rounded-full hover:bg-tg-hover flex items-center justify-center text-tg-subtext"><Settings size={20}/></button></div>
    <div className="px-3 pb-2"><div className="relative"><Search size={18} className="absolute right-3 top-1/2 -translate-y-1/2 text-tg-subtext"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جستجو..." className="w-full bg-tg-hover rounded-xl pr-10 pl-4 py-2 text-tg-text outline-none text-sm"/></div></div>
    <div className="px-2 pb-2 flex gap-1 overflow-x-auto"><button onClick={()=>setActiveFolder('all')} className={`shrink-0 px-3 py-1.5 rounded-lg text-xs ${activeFolder==='all'?'bg-tg-accent text-white':'bg-tg-hover text-tg-subtext'}`}>همه گفتگوها ({allCount})</button><button onClick={()=>setActiveFolder('archived')} className={`shrink-0 px-3 py-1.5 rounded-lg text-xs flex gap-1 items-center ${activeFolder==='archived'?'bg-tg-accent text-white':'bg-tg-hover text-tg-subtext'}`}><Archive size={13}/> بایگانی</button>{folders.map(f=><button key={f.id} onClick={()=>setActiveFolder(f.id)} className={`shrink-0 px-3 py-1.5 rounded-lg text-xs flex gap-1 items-center ${activeFolder===f.id?'bg-tg-accent text-white':'bg-tg-hover text-tg-subtext'}`}><Folder size={13}/>{f.name}</button>)}<button onClick={()=>setShowFolderCreator(true)} className="shrink-0 w-8 rounded-lg bg-tg-hover text-tg-subtext flex items-center justify-center"><FolderPlus size={15}/></button></div>
    {selected.size>0&&<div className="px-3 py-2 bg-tg-active flex items-center gap-2"><span className="text-sm text-tg-text flex-1">{selected.size} گفتگو انتخاب شده</span><button onClick={()=>{for(const id of selected)toggleArchive(id);setSelected(new Set())}} className="text-tg-text"><Archive size={17}/></button><button onClick={()=>{for(const id of selected)removeFromFolder(id);setSelected(new Set())}} className="text-tg-text"><X size={17}/></button><button onClick={()=>setSelected(new Set())}><X size={18}/></button></div>}
    <div className="flex-1 overflow-y-auto">{loading?<p className="text-center text-tg-subtext p-4">در حال بارگذاری...</p>:filtered.map(chat=>{const isOwner=chat.created_by===user?.id,isSaved=chat.type==='saved',title=isSaved?'پیام‌های ذخیره شده':(chat.title||'گفت‌وگو');return <div key={chat.id} className={`flex items-center gap-2 px-3 py-2.5 cursor-pointer relative ${selectedId===chat.id?'bg-tg-active':'hover:bg-tg-hover'} ${selected.has(chat.id)?'ring-2 ring-tg-accent':''}`} onPointerDown={()=>!isSaved&&startPress(chat.id)} onPointerUp={endPress} onPointerLeave={endPress} onClick={e=>{e.stopPropagation();if(longPressed.current){longPressed.current=false;return}if(selected.size){setSelected(v=>{const n=new Set(v);n.has(chat.id)?n.delete(chat.id):n.add(chat.id);return n})}else onSelect(chat.id)}}>
      <div className="relative">{isSaved?<div className="w-12 h-12 rounded-full bg-tg-accent/20 flex items-center justify-center"><Bookmark size={24} className="text-tg-accent"/></div>:<Avatar url={chat.avatar_url} name={title} size={48}/>}</div><div className="flex-1 min-w-0 text-right"><p className="text-tg-text font-medium truncate">{title}</p><p className="text-tg-subtext text-sm truncate">{chat.last_message||(chat.type==='direct'?(chat.other_online?'آنلاین':'گفت‌وگوی خصوصی'):chat.type==='group'?'گروه':'کانال')}</p></div><div className="flex flex-col items-end gap-1">{chat.last_message_time&&<span className="text-tg-subtext text-xs">{new Date(chat.last_message_time).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}</span>}{(unreadCounts[chat.id]||0)>0&&<span className="bg-tg-accent text-white text-xs rounded-full min-w-[20px] h-5 flex items-center justify-center px-1.5">{unreadCounts[chat.id]}</span>}</div>{!isSaved&&<button onClick={e=>{e.stopPropagation();setMenuChatId(menuChatId===chat.id?null:chat.id)}} className="w-8 h-8 rounded-full hover:bg-tg-active flex items-center justify-center text-tg-subtext"><MoreVertical size={17}/></button>}
      {menuChatId===chat.id&&!isSaved&&<div className="absolute top-full left-2 z-50 bg-tg-panel rounded-xl shadow-2xl border border-tg-hover py-1 min-w-[190px]" onClick={e=>e.stopPropagation()}><button onClick={()=>toggleArchive(chat.id)} className="w-full flex gap-2 px-4 py-2 text-sm text-tg-text hover:bg-tg-hover"><Archive size={16}/>{archived.includes(chat.id)?'خارج کردن از بایگانی':'بایگانی'}</button>{activeFolder!=='all'&&activeFolder!=='archived'&&<button onClick={()=>removeFromFolder(chat.id)} className="w-full flex gap-2 px-4 py-2 text-sm text-tg-text hover:bg-tg-hover"><X size={16}/>حذف از پوشه</button>}{activeFolder==='all'&&folders.length>0&&<div className="border-t border-tg-hover my-1 pt-1">{folders.map(f=><button key={f.id} onClick={()=>addFolder(chat.id,f.id)} className="w-full flex gap-2 px-4 py-2 text-sm text-tg-text hover:bg-tg-hover"><Folder size={15}/>{f.name}</button>)}</div>}<button onClick={()=>setSelected(v=>new Set(v).add(chat.id))} className="w-full flex gap-2 px-4 py-2 text-sm text-tg-text hover:bg-tg-hover"><MoreVertical size={16}/>انتخاب</button>{chat.type==='direct'&&<button onClick={()=>block(chat)} className="w-full flex gap-2 px-4 py-2 text-sm text-tg-red hover:bg-tg-hover"><Ban size={16}/>مسدود کردن</button>}<button onClick={()=>deleteChat(chat.id,isOwner)} className="w-full flex gap-2 px-4 py-2 text-sm text-tg-red hover:bg-tg-hover"><Trash2 size={16}/>{isOwner?'حذف گفت‌وگو':'ترک گفت‌وگو'}</button></div>}
    </div>})}{searchingPublic&&<p className="text-center text-tg-subtext text-sm p-4">در حال جست‌وجو...</p>}{publicResults.map(c=><div key={c.id} className="flex items-center gap-3 px-3 py-2.5 cursor-pointer hover:bg-tg-hover" onClick={()=>onPreviewChat(c.id)}><Avatar url={c.avatar_url} name={c.title||'گروه'} size={48}/><div className="flex-1"><p className="text-tg-text font-medium">{c.title||'گروه'}</p><p className="text-tg-subtext text-xs">{c.type==='channel'?'کانال عمومی':'گروه عمومی'}</p></div></div>)}</div>
    <button onClick={onNewChat} className="absolute bottom-4 left-4 w-14 h-14 rounded-full bg-tg-accent flex items-center justify-center shadow-lg"><Plus size={24} className="text-white"/></button><InstallModal open={showInstall} onClose={()=>setShowInstall(false)}/>
    {showFolderCreator&&<div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4" onClick={()=>setShowFolderCreator(false)}><div className="bg-tg-panel rounded-2xl p-5 w-full max-w-sm" onClick={e=>e.stopPropagation()}><h3 className="text-tg-text font-bold mb-3">پوشه جدید</h3><input autoFocus value={newFolder} onChange={e=>setNewFolder(e.target.value)} onKeyDown={e=>e.key==='Enter'&&createFolder()} className="w-full bg-tg-hover rounded-xl px-3 py-2 text-tg-text outline-none" placeholder="نام پوشه"/><div className="flex gap-2 mt-3"><button onClick={createFolder} className="flex-1 bg-tg-accent text-white rounded-xl py-2">ساختن</button><button onClick={()=>setShowFolderCreator(false)} className="flex-1 bg-tg-hover text-tg-text rounded-xl py-2">لغو</button></div></div></div>}
  </div>
}
